### ISSUE TITLE
Youtube annotations - Simple Video Embed

### ISSUE THREAD

**Issue by piyokii** [Almalerik/woocommerce-carousel-as#1]
Hello,
I use Simple Video Embed in my Wordpress site.  It works really well and am happy with it overall.  
One thing I cannot figure out is, how can you turn off the annotations without actually doing them on youtube?  Is there a code I can write somewhere?

**Comment by Almalerik** [comment]
Hi Piyokii,
sorry but I did not understand of which "annotations" you talk.
Can you explain better?

Cheers
Alma

**Comment by Almalerik** [comment]
Closed for no response.
